CREATE TABLE S0b_Struct.contract (
    acceptor_id BIGINT,
    assignee_id BIGINT,
    availability VARCHAR(20),
    collateral DECIMAL(18,2),
    contract_id BIGINT PRIMARY KEY,
    date_accepted DATETIME,
    date_completed DATETIME,
    date_expired DATETIME,
    date_issued DATETIME,
    days_to_complete INT,
    end_location_id BIGINT,
    for_corporation BOOLEAN,
    issuer_corporation_id BIGINT,
    issuer_id BIGINT,
    price DECIMAL(18,2),
    reward DECIMAL(18,2),
    start_location_id BIGINT,
    status VARCHAR(20),
    title TEXT,
    type VARCHAR(50),
    volume DECIMAL(18,2),
    character_name VARCHAR(100),
    contract_type VARCHAR(100),
    total_value DECIMAL(20,2)
);
